language: android

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
    - oraclejdk8

android:
    components:
        # Tools
        - tools
        # Build tools
        - build-tools-23.0.2

        # Android version
        - android-23

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

script:
    - ./gradlew build test
