language: android

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
    - oraclejdk8

before_install:
# Trick to make retrolambda working on Travis
# We need both Java 7 and Java 8, but the android source needs to be compiled with Java 7
# So we switch the JAVA_HOME environment to Java 7 before compiling
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA7_HOME
  
android:
    components:
        # Tools
        - tools
        # Build tools
        - build-tools-23.0.2

        # Android version
        - android-23

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
script:
    - ./gradlew build test
